### PR TITLE
Fix compilation error, warnings and migrate to 2018 edition

### PR DESCRIPTION
**Pull request by pheki**
Hey, thanks for this crate!

The crate wasn't compiling for me, so I've took the opportunity to fix the warnings. Note that after all those changes, the VPK size is still the same.

I made 4 commits:

1. Fix compilation errors in recent versions of rust, introduced by https://github.com/rust-lang/rust/pull/55632, the code was using repr(C) in enums which used values higher than isize::MAX (same as i32::MAX on vita), which is considered an overflow. Since C enums have no signedness guarantee, I only changed to repr(u32) those that would actually overflow.
2. I've fixed all warnings in the repository
3. I've derived `Copy` and `Clone` for `Sce` types, since they can be copied, are small and its how they're usually used in C. While at it, also derived `Debug`. I've removed `#![feature(untagged_unions)]` since its no longer needed.
4. I've migrated the crates the code to the Rust 2018 edition by following the [Edition Guide](https://doc.rust-lang.org/nightly/edition-guide/editions/transitioning-an-existing-project-to-a-new-edition.html). If you'd rather maintain the crate in the 2015 edition, I'll just remove this commit.

I also needed to update to patch `rust-script` as it wasn't detecting the `fn main()` in some `cargo-make` scripts: https://github.com/fornwall/rust-script/pull/18

What do you think?

### CODE REVIEW

**Comment by althonos** [comment]
Thanks a lot! Nice job cleaning up everything. (I replied to your e-mail earlier as well btw).
